name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: input-output-hk/devx-devcontainer
  REGISTRY: ghcr.io
  DEFAULT_TAG: latest

jobs:
  build_and_push:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    # We want a GitHub Codespace image for each combination of devx developer shell option.
    # But, since the purpose of GitHub Codespace is to serve a complete development environment,
    # the user is likely to always expect HLS (I don't see the point otherwise).
    # Therefore, it doesn't seem useful to build an image on the `-minimal` flavor (without HLS),
    # or the `-static` one (especially since the latter currently requires `-minimal` to work).
    # Likely, we consider using `-iog` as the default and do not generate other images.
    # Then the user choices left would be between native, `-windows` or `-js` target platforms,
    # and the GHC version (currently `ghc8107` and `ghc962`).
    strategy:
      matrix:
        platform: ['x86_64-linux']
        target-platform: ['', '-windows', '-js']
        compiler-nix-name: ['ghc8107','ghc962']
        minimal: [false]
        iog: [true]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.compiler-nix-name }}${{ matrix.target-platform }}-iog
        build-args: |
          platform=${{ matrix.platform }}
          target-platform=${{ matrix.target-platform }}
          compiler-nix-name=${{ matrix.compiler-nix-name }}
          minimal=${{ matrix.minimal }}
          iog=${{ matrix.iog }}
