name: Test that we can build the hello world example form hackage
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Nix with good defaults
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install jq
        run: |
          curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq
          chmod +x jq
      - name: Download and import closure
        run: |
          ./fetch-docker.sh andreabedini/closure 0 | zstd -d | nix-store --import | tee store-paths.txt
          ln -s $(tail -n 1 store-paths.txt) env.sh
      - name: cabal update
        run: |
          source env.sh &&
          cabal update
      - name: build hello
        run: |
          source env.sh &&
          cabal unpack hello-1.0.0.2 &&
          cd hello-1.0.0.2 &&
          cabal update &&
          cabal build &&
          cabal test
