name: Test that we can build the hello world example form hackage
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: devx {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-darwin  
          - x86_64-linux 
          #- aarch64-darwin  
          #- aarch64-linux 
        compiler-nix-name:
          - ghc8107
          - ghc927
          - ghc961
        target-platform:
          - ""
          - "-static"
          - "-js"
        variant:
          - ""
          - "-minimal"
        iog:
          - ""
          - "-iog"
        os:
          - ubuntu-latest
          #- macOS-latest
        exclude:
          - compiler-nix-name: ghc8107
            target-platform: "-js"
          - compiler-nix-name: ghc927
            target-platform: "-js"
          - platform: x86_64-darwin
            target-platform: "-static"
          - target-platform: "-static"
            variant: ""
          - target-platform: ghc961
            variant: ""

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Nix with good defaults
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install jq
        shell: bash
        run: |
          curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq
          chmod +x jq
      - name: Download and import closure
        shell: bash
        run: |
          ./fetch-docker.sh input-output-hk/devx ${{ matrix.compiler-nix-name }}${{ matrix.target-platform }}${{ matrix.variant }}${{ matrix.iog }}-env.${{ matrix.platform }} | zstd -d | nix-store --import | tee store-paths.txt
          sudo ln -s $(tail -n 1 store-paths.txt) /usr/bin/devx-env.sh
          sudo cp extra/devx /usr/bin
      - name: Check cabal wrapper
        run: |
          echo "NIX_CABAL_FLAGS=$NIX_CABAL_FLAGS"
          which cabal
          file $(which cabal)
          cat $(which cabal)
      - name: cabal update
        run: cabal update
      - name: unapck hello
        run: cabal unpack hello
      - name: build hello
        working-directory: hello-1.0.0.2
        run: cabal build
      - name: test hello
        working-directory: hello-1.0.0.2
        run: cabal test
