name: Test that we can build the hello world example form hackage
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: devx {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          #- x86_64-darwin
          - x86_64-linux
          # Skipping because we do not have runners for these set up.
          #- aarch64-darwin
          #- aarch64-linux
        compiler-nix-name:
          #- ghc8107
          #- ghc927
          - ghc961
        target-platform:
          #- ""
          - "-static"
          #- "-js"
          - "-windows"
        minimal:
          #- false
          - true
        iog:
          - false
          #- true
        exclude:
          # Just cross compiling javascript with ghc 9.6.1 for now
          - compiler-nix-name: ghc8107
            target-platform: "-js"
          - compiler-nix-name: ghc927
            target-platform: "-js"
          # Static builds not working for darwin yet
          - platform: x86_64-darwin
            target-platform: "-static"
          # Static tools not working right now (so just building "-static-minimal" for now)
          - target-platform: "-static"
            minimal: false
          # hlint and hls not working on ghc 9.6.1 yet
          - target-platform: ghc961
            minimal: false
          # Windows cross compilation only works on x86_64 right now.
          - platform: aarch64-darwin
            target-platform: "-windows"
          - platform: aarch64-linux
            target-platform: "-windows"
          # Also broken for darwin.
          - platform: x86_64-darwin
            target-platform: "-windows"

    runs-on: ${{ matrix.platform == 'x86_64-linux' && 'ubuntu-latest' || 'macos-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install GHC and Cabal
        uses: input-output-hk/actions/devx@latest
        with:
          platform: ${{ matrix.platform }}
          target-platform: ${{ matrix.target-platform }}
          compiler-nix-name: ${{ matrix.compiler-nix-name }}
          minimal: ${{ matrix.minimal }}
          iog: ${{ matrix.iog }}
      - name: cabal update
        run: cabal update
      - name: unapck hello
        run: cabal unpack hello
      - name: build hello
        working-directory: hello-1.0.0.2
        run: |
          cabal build${{ matrix.target-platform == '-static' && ' --enable-executable-static' || '' }}
          mkdir bin
          cp dist-newstyle/build/${{ matrix.platform }}/*/hello-1.0.0.2/build/hello/hello bin
      - name: install hello
        working-directory: hello-1.0.0.2
        run: cabal install --installdir bin
      - name: Upload hello executable
        uses: actions/upload-artifact@v3
        with:
          name: hello-${{ matrix.platform }}${{ matrix.target-platform }}${{ matrix.minimal && '-minimal' || '' }}${{ matrix.iog && '-iog' || '' }}
          path: hello-1.0.0.2/bin/hello${{ matrix.target-platform == '-windows' && '.exe' || '' }}

  run:
    name: Run executable
    needs: build

    strategy:
      fail-fast: false
      matrix:
        platform:
          #- x86_64-darwin
          - x86_64-linux
          # Skipping because we do not have runners for these set up.
          #- aarch64-darwin
          #- aarch64-linux
        compiler-nix-name:
          #- ghc8107
          #- ghc927
          - ghc961
        target-platform:
          #- ""
          - "-static"
          #- "-js"
          - "-windows"
        minimal:
          #- false
          - true
        iog:
          - false
          #- true
        exclude:
          # Just cross compiling javascript with ghc 9.6.1 for now
          - compiler-nix-name: ghc8107
            target-platform: "-js"
          - compiler-nix-name: ghc927
            target-platform: "-js"
          # Static builds not working for darwin yet
          - platform: x86_64-darwin
            target-platform: "-static"
          # Static tools not working right now (so just building "-static-minimal" for now)
          - target-platform: "-static"
            minimal: false
          # hlint and hls not working on ghc 9.6.1 yet
          - target-platform: ghc961
            minimal: false
          # Windows cross compilation only works on x86_64 right now.
          - platform: aarch64-darwin
            target-platform: "-windows"
          - platform: aarch64-linux
            target-platform: "-windows"
          # Also broken for darwin.
          - platform: x86_64-darwin
            target-platform: "-windows"

    runs-on: ${{ matrix.target-platform == '-windows' && ' windows-latest' || (matrix.platform == 'x86_64-linux' && 'ubuntu-latest' || 'macos-latest') }}
    steps:
      - name: Download hello executable
        uses: actions/download-artifact@v3
        with:
          name: hello-${{ matrix.platform }}${{ matrix.target-platform }}${{ matrix.minimal && '-minimal' || '' }}${{ matrix.iog && '-iog' || '' }}
      - shell: bash
        name: Run hello executable
        run: |
          ls -l .
          chmod +x hello
          ls -l
          file hello
          ./hello
