name: Prebuild DevX closures
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        devshell:
          #- ghc8107
          #- ghc902
          #- ghc927
          #- ghc8107-minimal
          #- ghc902-minimal
          #- ghc927-minimal
          #- ghc8107-static-minimal
          #- ghc902-static-minimal
          - ghc927-static-minimal
        os:
          - ubuntu-latest
          #- macOS-latest
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix with good defaults
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=
            substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Compute and upload closure and developer environment to ghcr.io
        env:
          NIX_STORE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FLAKE_DEV_SHELL: ${{ matrix.devshell }}
        run: ./extra/ghcr-upload.sh
