name: Prebuild DevX closures
on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-darwin  
          - x86_64-linux 
          - aarch64-darwin  
          - aarch64-linux 
        compiler-nix-name:
          - ghc8107
          - ghc927
          - ghc961
        target-platform:
          - ""
          - "-static"
          - "-js"
          - "-windows"
        variant:
          - ""
          - "-minimal"
        iog:
          - ""
          - "-iog"
        os:
          - ubuntu-latest
          #- macOS-latest
        exclude:
          - compiler-nix-name: ghc8107
            target-platform: "-js"
          - compiler-nix-name: ghc927
            target-platform: "-js"
          - platform: x86_64-darwin
            target-platform: "-static"
          - target-platform: "-static"
            variant: ""
          - target-platform: ghc961
            variant: ""
          - platform: aarch64-darwin
            target-platform: "-windows"
          - platform: aarch64-linux
            target-platform: "-windows"
        
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Nix with good defaults
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=
            substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute and upload closure and developer environment to ghcr.io
        env:
          NIX_STORE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEV_SHELL: ${{ matrix.platform }}.${{ matrix.compiler-nix-name }}${{ matrix.target-platform }}${{ matrix.variant }}${{ matrix.iog }}-env
        run: ./extra/ghcr-upload.sh
